# @todo Install 'sp' package and remove VALIDATE bypass.

language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gawk lzip

script:
  - make AWK=gawk VALIDATE=':' VERSION=-$(git rev-parse --short HEAD) tarballs_version
